### ISSUE TITLE
DeAuthentication on 2021 16inch Mac 

### ISSUE THREAD

**Issue by ShadowRoi** [phenotypic/WiFiCrackPy#3]
Hello and thanks for sharing this projects it works really great and makes things very simple.

While everything seems to work good with the test that I made on my router, I had seen that the DeAuthentication doesn’t work on my Mac just how it was expected and mentioned in the project. 

I am not sure if I am using the arguments correctly because I think I am not forcing zizzania to do it at all. In order to force it I use the -d parameter when launching the script? 

Like “python3 WifiCrackPy -d”? Also is there a possible work around for the DeAuthentication to make it work? Is there any other known script that I may use to Deauthenticate while zizzania is looking to grab a handshake to speed up the process? 

And a last question. If I am far away from my router and it doesn’t have a strong signal like around -70db can it “miss” a handshake? Does this require you to have a very strong signal and be very close to grab the handshake or maybe physically somewhere between the client and the AP to “grab” it? I was wondering if a client is on the other side of a router if it will be able to catch a handshake

**Comment by phenotypic** [comment]
Hi there, as mentioned in the README, `zizzania` has the ability to send deauthentication frames, but this is disabled by default as newer Macs have compatibility issues (~2018 onwards, so your Mac is included). You can activate the deauthentication feature using the `-d` parameter, e.g. ` python3 WiFiCrackPy.py -d`.

The script needs to be able to capture the relevant handshake frames in order to crack the hash. If the signal is too weak, you may not be able to do capture the frames. The physical positioning (client, router, intercept) doesn't matter as long as the intercept can 'hear' the relevant frames.

**Comment by phenotypic** [comment]
@MrWijnen01 Hi there, please see the response above. There are compatibility issues with newer Macs, including the M1.

**Comment by MrWijnen01** [comment]
I used -d but it does nothing.

**Comment by mgd722** [comment]
For clarity, if your network card does not support injection you should not expect deauthentication to work even if you pass the `-d` flag. The [onboard network card on most (all?) later Macs does not seem to support this](https://github.com/cyrus-and/zizzania/issues/14), so you'd need an external network interface in order to force deauth. If you wait and catch normal network events though, the rest of this script works as expected.
